#!\xampp\php\php.exe
<?php
/**
 * Generate text phpinfo() style PEAR information, for CLI.
 *
 * PHP versions 4 and 5
 *
 * @category PEAR
 * @package  PEAR_Info
 * @author   Laurent Laville <pear@laurent-laville.org>
 * @license  http://www.php.net/license/3_01.txt  PHP License 3.01
 * @version  CVS: $Id: pearinfo,v 1.1 2008/03/23 10:14:39 farell Exp $
 * @link     http://pear.php.net/package/PEAR_Info
 * @since    File available since Release 1.8.0
 */

require_once 'PEAR/Info/Cli.php';

$cli = new PEAR_Info_Cli();
$cli->run();
?>